app/rqalpha/__init__.py
from flask import Blueprint

rqalpha = Blueprint('rqalpha', __name__)

from . import views

app/rqalpha/views.py
from flask import render_template, session, redirect, url_for, Flask, request, flash, jsonify
from numpy.core.multiarray import ndarray

from . import rqalpha
import os
from multiprocessing import Process
import sys
sys.path.insert(0, "Z:\Hello\Work\Data\QT")
from rqalpha import run_code
from .. import db
from ..models import Role, User, Strategy
from flask_login import login_required, current_user
import pickle as pk
import numpy as np
import time
import datetime
import json
name = None


@rqalpha.route('/result/<strategyname>', methods=['GET'])
@login_required
def result(strategyname):
    strategy = Strategy.query.filter_by(
        strategyname=strategyname, author=current_user._get_current_object()).first_or_404()
    start_date = strategy.startdate
    end_date = strategy.enddate
    stock = strategy.stock
    source_code = strategy.code
    return render_template('rqalpha/result.html', strategyname=strategyname, start_date=start_date, end_date=end_date, stock=stock, source_code=source_code)


@rqalpha.route('/result', methods=['GET'])
@login_required
def new_result():
    strategyname = "Demo"
    start_date = "2016-01-04"
    end_date = "2016-10-04"
    stock = "1000000"
    source_code = """
# 可以自己import我们平台支持的第三方python模块，比如pandas、numpy等。

# 在这个方法中编写任何的初始化逻辑。context对象将会在你的算法策略的任何方法之间做传递。
def init(context):
    context.s1 = "000001.XSHE"
    # 实时打印日志
    logger.info("Interested at stock: " + str(context.s1))

# before_trading此函数会在每天交易开始前被调用，当天只会被调用一次
def before_trading(context, bar_dict):
    pass


# 你选择的证券的数据更新将会触发此段逻辑，例如日或分钟历史数据切片或者是实时数据切片更新
def handle_bar(context, bar_dict):
    # 开始编写你的主要的算法逻辑javascript:void(0)

    # bar_dict[order_book_id] 可以拿到某个证券的bar信息
    # context.portfolio 可以拿到现在的投资组合状态信息

    # 使用order_shares(id_or_ins, amount)方法进行落单

    # TODO: 开始编写你的算法吧！
    order_shares(context.s1, 1000)
    """
    return render_template('rqalpha/result.html', strategyname=strategyname, start_date=start_date, end_date=end_date, stock=stock, source_code=source_code)


def k_strategy(code, filename, start_date, end_date, account_stock, benchmark="000300.XSHG"):
    config = {"base": {"start_date": start_date, "end_date": end_date, "benchmark": benchmark,
                       "accounts": {"stock": account_stock}},
              "extra": {"log_level": "verbose", },
              "mod": {"sys_analyser": {"enabled": True,
                                       "output_file": "Z:/Hello/Work/Data/QT/Rqalpha_test/HHH/app/static/test-result/" + filename}}}
    #"plot_save_file": "Z:/Hello/Work/Data/QT/Rqalpha_test/HHH/app/static/test-result/" + filename ,

    run_code(code, config)


def query_db(p, testNum=3):
    if testNum != 0:
        try:
            with open('Z:/Hello/Work/Data/QT/Rqalpha_test/HHH/app/static/test-result/' + name + str(p), 'rb') as f:
                m = pk.load(f)
            return m
        except FileNotFoundError:
            testNum -= 1
            time.sleep(0.25)
            return query_db(p, testNum)
    else:
        return


# noinspection PyGlobalUndefined
@rqalpha.route("/result/weather", methods=["GET", "POST"])
def weather():
    if name != None:
        if request.method == "POST":

            p = int(request.form['nm'])
            print(p)
            m = query_db(p)
            if m:
                i = (int(request.form['id']))
                print("i", i)
                summary = m['summary']
                total_returns = summary['total_returns']
                annualized_returns = summary['annualized_returns']
                benchmark_total_returns = summary['benchmark_total_returns']
                benchmark_annualized_returns = summary[
                    'benchmark_annualized_returns']
                sharpe = summary['sharpe']

                portfolio_1 = m['portfolio'][i:i + 300]
                benchmark_portfolio = m['benchmark_portfolio'][i:i + 300]
                date = [i for i in portfolio_1.unit_net_value.index]
                v1 = [i for i in portfolio_1.unit_net_value.values - 1]
                v2 = [i for i in benchmark_portfolio.unit_net_value.values - 1]

                portfolio = m['portfolio'][:i + 300]
                index = portfolio.index
                portfolio_value = portfolio.unit_net_value * portfolio.units
                xs = portfolio_value.values
                rt = portfolio.unit_net_value.values
                xs_max_accum = np.maximum.accumulate(xs)
                max_dd_end = np.argmax(xs_max_accum / xs)
                if max_dd_end == 0:
                    max_dd_end = len(xs) - 1
                tmp = (xs - xs_max_accum)[max_dd_end:]
                max_dd_start = np.argmax(
                    xs[:max_dd_end]) if max_dd_end > 0 else 0
                max_ddd_start_day = max_dd_start
                max_ddd_end_day = len(
                    xs) - 1 if tmp.max() < 0 else np.argmax(tmp) + max_dd_end

                max_dd_info = "MaxDD  {}~{}, {} days".format(str(index[max_dd_start]), str(index[max_dd_end]),
                                                             (index[max_dd_end] - index[max_dd_start]).days)
                max_ddd_info = "MaxDDD {}~{}, {} days".format(str(index[max_ddd_start_day]), str(index[max_ddd_end_day]),
                                                              (index[max_ddd_end_day] - index[max_ddd_start_day]).days)
                my_file = 'Z:/Hello/Work/Data/QT/Rqalpha_test/HHH/app/static/test-result/' + \
                    name + str(p)
                if os.path.exists(my_file):
                    os.remove(my_file)
            else:
                date = []
                v1 = []
                v2 = []
                total_returns = ""
                annualized_returns = ""
                benchmark_total_returns = ""
                benchmark_annualized_returns = ""
                sharpe = ""
                max_dd_info = ""
                max_ddd_info = ""
    else:
        date = []
        v1 = []
        v2 = []
        total_returns = ""
        annualized_returns = ""
        benchmark_total_returns = ""
        benchmark_annualized_returns = ""
        sharpe = ""
        max_dd_info = ""
        max_ddd_info = ""

    return jsonify(month=date,
                   evaporation=v1,
                   precipitation=v2,
                   total_returns=total_returns,
                   annualized_returns=annualized_returns,
                   benchmark_total_returns=benchmark_total_returns,
                   benchmark_annualized_returns=benchmark_annualized_returns,
                   sharpe=sharpe,
                   maxDD=max_dd_info,
                   maxDDD=max_ddd_info)  # 返回json格式


@rqalpha.route("/hot", methods=["GET", "POST"])
def hot():
    global name
    name = request.form.get('strategy_name')
    start_date = request.form.get('start_date')
    end_date = request.form.get('end_date')
    stock = request.form.get('stock_value')
    code = request.form.get('code')
    save_or_not = request.form.get('saveornot')
    if save_or_not == "true":
        strategy = Strategy.query.filter_by(
            strategyname=name, author=current_user._get_current_object()).first()
        if strategy is not None:
            db.session.delete(strategy)
            db.session.commit()
            db.session.add(Strategy(strategyname=name, startdate=datetime.datetime.strptime(start_date, "%Y-%m-%d"),
                                    enddate=datetime.datetime.strptime(end_date, "%Y-%m-%d"), stock=int(stock), code=code, author=current_user._get_current_object()))
            db.session.commit()
        else:
            strategy = Strategy(strategyname=name, startdate=datetime.datetime.strptime(start_date, "%Y-%m-%d"), enddate=datetime.datetime.strptime(
                end_date, "%Y-%m-%d"), stock=int(stock), code=code, author=current_user._get_current_object())
            db.session.add(strategy)
            db.session.commit()
        flash('Your strategy has been saved successfully.')
    for i in range(20):
        my_file = 'Z:/Hello/Work/Data/QT/Rqalpha_test/HHH/app/static/test-result/' + \
            name + str(i - 1)
        if os.path.exists(my_file):
            os.remove(my_file)
    p = Process(target=k_strategy, args=(
        code, name, start_date, end_date, int(stock)))
    p.start()
    return 'ok'

app/templates/rqalpha/result.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}My Strategy{% endblock %}

{% block head %}
<script src="{{ url_for('static', filename='jquery-3.1.1.js') }}"></script>
<script src="{{ url_for('static', filename='echarts.js') }}"></script>
<script src="http://code.jquery.com/jquery-1.8.0.min.js" type="text/javascript"></script>
<script src="../../static/ace/build/src/ace.js" type="text/javascript"></script>
<script src="../../static/ace/build/src/mode-python.js" type="text/javascript"></script>
<script type="text/javascript" src="../../static/My97DatePicker/WdatePicker.js"></script>

{{ super() }}

{% endblock %}

{% block page_content %}

<style type="text/css">

.result-container{
    display: flex;
    flex-direction: row;
    width: 1400px;
    height: auto;
}
#code-area{
    width: 600px;
    height:450px;
    border-right:1px;
    border-right-style: solid;
    border-right-color: #999;
}
.picture{
    display: flex;
    flex-direction: column;
}
#main2 {
    height:100px;
    width: 700px;
    padding:10px;
    padding-left: 20px;
}
#main {
    height:300px;
    width:700px;
    padding:10px;
    padding-left: 20px;
}
.selection-area{
    width: 100%;
    height: 50px;
    border-color: #666; 
    display: flex;
    flex-direction: row;  
}
.container{
    display: flex;
    flex-direction: column;
}




</style>
<div class="container">
    <div class="selection-area">
        <form method="POST" id="form1">
           <p>Please input your strategy name:&nbsp;&nbsp;<input type="text" id="sname" value={{strategyname}} />&nbsp;&nbsp;From&nbsp;&nbsp;<input type="text" id="startdate" onClick="WdatePicker()" readonly="readonly" value={{start_date}} />&nbsp;&nbsp;To&nbsp;&nbsp;<input type="text" id="enddate" onClick="WdatePicker()" readonly="readonly" value={{end_date}} />&nbsp;&nbsp;Stock ¥&nbsp;&nbsp;<input type="text" id="stock" value={{stock}} />&nbsp;&nbsp;<input type="checkbox" id="savebox" />&nbsp;&nbsp;Save Strategy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="button" name="submit" value="Submit" style="background-color:#00BFFF; width:120px; height:40px; color:#FFFFFF; border:none; border-radius: 8px;" onmouseover="this.style.backgroundColor='#4169E1';" onmouseout="this.style.backgroundColor='#00BFFF';" onclick="transfer_data()"/></p>
           
       </form>

    </div>
    <div class='result-container'>
        <div id="code-area"></div>
        <div class='picture'>
            <div id="main2"></div>
            <div id="main"></div>
        </div>
    </div>
</div>



<!--为ECharts准备一个具备大小（宽高）的Dom-->


<script type="text/javascript">
    //--- 折柱 ---
    var myChart = echarts.init(document.getElementById('main'));




    myChart.setOption({
        title: {
            text: '回测示例'
        },
        tooltip: {},
        legend: {
            data:['portfolio','benchmark_portfolio']
        },
        toolbox: {
            show: true,
            feature: {
                dataZoom: {
                    yAxisIndex: 'none'
                },
                dataView: {readOnly: false},
                magicType: {type: ['line', 'bar']},
                restore: {},
                saveAsImage: {}
            }
        },
        xAxis: {
            name: 'Days',
            data: []
        },
        yAxis: {
            name:"累积收益"
        },
        dataZoom: [
        {   // 这个dataZoom组件，默认控制x轴。
            type: 'slider', // 这个 dataZoom 组件是 slider 型 dataZoom 组件
            start: 0,      // 左边在 0% 的位置。
            end: 100         // 右边在 100% 的位置。
        }
        ],
        series: [{
            name: 'portfolio',
            type: 'line',
            data: []
        },{
            name: 'benchmark_portfolio',
            type: 'line',
            data: []
        },]
    });


    var myChart2 = echarts.init(document.getElementById('main2'));
    option2 = {
        series: [
        {
            type: 'scatter',
            data: [
            {
                value: [0,0],
                label: {
                    normal: {
                        formatter: [
                        '{tc|Summary}{titleBg|}',
                        String([]),
                        ].join('\n'),
                        rich: {
                            titleBg: {
                                align: 'right'
                            }
                        }
                    }
                }
            },

            ],
            symbolSize: 1,
            label: {
                normal: {
                    show: true,
                    backgroundColor: '#ddd',
                    borderColor: '#555',
                    borderWidth: 1,
                    borderRadius: 5,
                    color: '#000',
                    fontSize: 14,
                    rich: {
                        titleBg: {
                            backgroundColor: '#000',
                            height: 30,
                            borderRadius: [5, 5, 0, 0],
                            padding: [0, 10, 0, 10],
                            width: '100%',
                            color: '#eee'
                        },
                        tc: {
                            align: 'center',
                            color: '#eee'
                        },
                        hr: {
                            borderColor: '#777',
                            width: '100%',
                            borderWidth: 0.5,
                            height: 0
                        },

                    }
                }
            }
        }
        ],
        xAxis: {
            axisLabel: {show: false},
            axisLine: {show: false},
            splitLine: {show: false},
            axisTick: {show: false},
            min: -1,
            max: 1
        },
        yAxis: {
            axisLabel: {show: false},
            axisLine: {show: false},
            splitLine: {show: false},
            axisTick: {show: false},
            min: 0,
            max: 2,
            inverse: true
        }
    };

    myChart2.setOption(option2);

    // 四个全局变量：月份、蒸发量、降水量、  哨兵（用于POST）
    var month = [],
    evaporation = [],
    precipitation = [],
        number = 1,//pickle_record_number
        lastID = 0; // 哨兵，记录上次数据表中的最后id +1（下次查询只要>=lastID）
    var timeTicket

function cleanData(){
        number = 1,//pickle_record_number
        lastID = 0; // 哨兵，记录上次数据表中的最后id +1（下次查询只要>=lastID）
    }

    //准备好统一的 callback 函数
    var update_mychart = function (data) { //data是json格式的response对象

        myChart.hideLoading(); // 隐藏加载动画

        dataLength = data.month.length //取回的数据长度
        lastID += dataLength //哨兵，相应增加。
        number += 1 //pickle(x)
        console.log("num")
        if (!dataLength || dataLength == 0){
        console.log("clean");
        clearInterval(timeTicket);
        cleanData();
        return;} //如果取回的数据长度为0,停止ajax
        // 切片是能统一的关键！！
        month = month.concat(data.month) // 数组，先切片、再拼接
        evaporation = evaporation.concat(data.evaporation.map(parseFloat)) //注意map方法
        precipitation = precipitation.concat(data.precipitation.map(parseFloat))
        var total_returns = data.total_returns
        var annualized_returns = data.annualized_returns
        var benchmark_total_returns = data.benchmark_total_returns
        var benchmark_annualized_returns = data.benchmark_annualized_returns
        var sharpe = data.sharpe
        var maxDD = data.maxDD
        var maxDDD = data.maxDDD

        // 填入数据
        myChart.setOption({
            legend: {
                data:['portfolio','benchmark_portfolio']
            },
            xAxis: {
                data: month
            },
            series: [{
                name: 'portfolio', // 根据名字对应到相应的系列
                data: evaporation
            },{
                name: 'benchmark_portfolio',
                data: precipitation
            }]
        });


        option2 = {
            series: [
            {
                type: 'scatter',
                data: [
                {
                    value: [0,0],
                    label: {
                        normal: {
                            formatter: [
                            '{tc|Summary}{titleBg|}',
                            '{tr|回测收益}' + "    " + '{tr|回测年化收益}' + "    " + '{tb|基准收益}' + "    " + '{tb|基准年化收益}' + "    " + '{tc|夏普比率}',
                            String(total_returns) + '          ' + String(annualized_returns) + '           ' + String(benchmark_total_returns) + '         ' + String(benchmark_annualized_returns) + '          ' + String(sharpe),
                            ].join('\n'),
                            rich: {
                                titleBg: {
                                    align: 'right'
                                }
                            }
                        }
                    }
                },

                ],
                symbolSize: 1,
                label: {
                    normal: {
                        show: true,
                        backgroundColor: '#eee',
                        borderColor: '#fff',
                        borderWidth: 1,
                        borderRadius: 5,
                        color: '#000',
                        fontSize: 14,
                        rich: {
                            titleBg: {
                                backgroundColor: '#fff',
                                height: 30,
                                borderRadius: [5, 5, 0, 0],
                                padding: [0, 10, 0, 10],
                                width: '100%',
                                color: '#eee'
                            },
                            tc: {
                                align: 'center',
                                color: '#000'
                            },
                            tr:{
                                align:'center',
                                color:'#911'
                            },
                            tb:{
                                align:'center',
                                color:'#32e'
                            },
                            hr: {
                                borderColor: '#777',
                                width: '100%',
                                borderWidth: 0.5,
                                height: 0
                            },

                        }
                    }
                }
            }
            ],
            xAxis: {
                axisLabel: {show: false},
                axisLine: {show: false},
                splitLine: {show: false},
                axisTick: {show: false},
                min: -1,
                max: 1
            },
            yAxis: {
                axisLabel: {show: false},
                axisLine: {show: false},
                splitLine: {show: false},
                axisTick: {show: false},
                min: 0,
                max: 2,
                inverse: true
            }
        };
        myChart2.setOption(option2);
        window.addEventListener("resize", function () {
          myChart.resize();
          myChart2.resize();
      });
    }




    //以下是ace-editor功能
    var editor = ace.edit("code-area");
    editor.setTheme("ace/theme/chrome");
    editor.getSession().setMode("ace/mode/python");
    var editorValue = ({{source_code|tojson}});
    editor.setValue(editorValue);
    editor.moveCursorTo(0, 0);

    // 以下是ajax传输表单数据

function transfer_data(){
    var data={
        'strategy_name':document.getElementById("sname").value,
        'start_date':document.getElementById("startdate").value,
        'end_date':document.getElementById("enddate").value,
        'stock_value':document.getElementById("stock").value,
        'saveornot':document.getElementById("savebox").checked,
        'code':editor.getValue(),
    };
    $.ajax({
        type:'POST',
        url:'{{url_for("rqalpha.hot")}}',
        data: data,
        dataType:'json',//希望服务器返回json格式的数据\

        success:function(data){
            console.log("HAHA");

                    },
        error:function(data){
            console.log("HEHE");
        }

    });

        myChart.showLoading(); // 首次显示加载动画


    // 异步加载数据 （首次，get，显示6个数据）
    //$.post('/rqalpha/result/weather').done(update_mychart);


    // 异步更新数据 （以后，定时post，取回1个数据）
    timeTicket = setInterval(function () {
        $.post('/rqalpha/result/weather',{id: lastID,nm: number}).done(update_mychart);
    }, 5000);

}

</script>


{% endblock %}